name: Automation Workflow
on: workflow_dispatch
env:
  TEST_PROJECT_NAME: HeroKuAppAutomation/HeroKuAppAutomation.csproj
jobs:
  selenium_test:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up .NET CLI
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

    - name: Install dependencies
      run: dotnet restore ${{ env.TEST_PROJECT_NAME }}

    - name: Build the project
      run: dotnet build ${{ env.TEST_PROJECT_NAME }}
