name: Automation Workflow
on: workflow_dispatch
jobs:
  build:
    runs-on: windows-latest
    steps:
     - name: setup-msbuild
       uses: microsoft/setup-msbuild@v1.3.1
     - name: Build app for release
       run: msbuild HeroKuAppAutomation\HeroKuAppAutomation\HeroKuAppAutomation.csproj -verbosity:diag -property:Configuration=Debug
